# Generated by Django 4.2.4 on 2023-09-03 22:07

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('type', models.CharField(max_length=10, null=True)),
                ('operator_name', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('division', models.CharField(max_length=50, null=True)),
                ('emp_position', models.CharField(max_length=50, null=True)),
                ('pf_no', models.IntegerField(null=True)),
                ('contact_no', models.IntegerField(null=True)),
                ('org_contact_no', models.IntegerField(null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to=users.models.upload_to)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to=users.models.upload_to)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
