# Generated by Django 4.2.4 on 2023-09-24 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('type', models.CharField(max_length=10, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=50)),
                ('operator_name', models.CharField(max_length=50)),
                ('emp_position', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('org_contact_no', models.IntegerField()),
                ('address', models.TextField(max_length=500, null=True)),
                ('location', models.CharField(max_length=50)),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to=users.models.upload_to)),
                ('corporation_proof', models.FileField(blank=True, null=True, upload_to=users.models.upload_to)),
                ('allocated', models.BooleanField(default=False)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('consumer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.consumeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='RailwayAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('operator_name', models.CharField(max_length=50, null=True)),
                ('division', models.CharField(max_length=50, null=True)),
                ('pf_no', models.IntegerField(null=True)),
                ('contact_no', models.IntegerField(null=True)),
                ('org_contact_no', models.IntegerField(null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to=users.models.upload_to)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to=users.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Rake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.IntegerField()),
                ('operator', models.CharField(max_length=50, null=True)),
                ('destination', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.consumeraccount')),
                ('railway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.railwayaccount')),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.companyaccount')),
            ],
        ),
    ]
