# Generated by Django 4.2.4 on 2023-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_rake_destination_alter_rake_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='stock',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
